# Welcome to the essentail Data Librarires Bootcamp!

## Intro
In this bootcamp, we will introduce three essential Python libraries for data science: NumPy, and Pandas. We will guide you through using Jupyter Notebook, an open-source web application that allows you to create and share documents that contain live code, equations, visualizations, and narrative text.

****

Before we start, make sure you have Python, Jupyter Notebook, and the necessary libraries installed. 

You can install them using pip. Just run the cell bellow if you have not done so yet

BASH

$pip install jupyter

In [1]:
!pip install numpy pandas matplotlib

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/65/5b/3b8fd7d66043f0638a35fa650570cbe69efd42fe169e5024f9307598b47e/matplotlib-3.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/b7/f6/78f60fa0b6ae64971178e2542e8b3ad3ba5f4f379b918ab7b18038a3f897/contourpy-1.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for cycler>=0.10 from https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl.metadata
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/72/2c/7634a6c16b29d0c31cf54051beefab796abdfe8f52abead6d09e5403696e/fonttools-4.43.1-cp311-cp311-manylinux_2_17_x86_64.many

## Numpy

NumPy (Numerical Python) is a Python library used for numerical computations and working with arrays. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To start, we will import numpy

In [2]:
import numpy as np #import module as _someShortCut

### Numpy Operations

Bellow are some examples of how to create, do opperations, and index an array. There more complicated things that you can do witn numpy arrays, but we will stick with the basics for now.

In [3]:
# Creating arrays
a = np.array([1, 2, 3])   
print(a)

# Basic operations
b = np.array([4, 5, 6]) 
print(a + b)

# Indexing
print(a[0])

# Changing an element of the array
a[0] = 5
print(a)

[1 2 3]
[5 7 9]
1
[5 2 3]


Notice how they are different to regular lists. Here are some examples of how numpy arrays differ from lists

In [4]:
# Python list operations
list1 = [1, 2, 3]
list2 = [4, 5, 6]

# This will concatenate the two lists
print(list1 + list2)  # Outputs: [1, 2, 3, 4, 5, 6]

# This will repeat list1 three times
print(list1 * 3)  # Outputs: [1, 2, 3, 1, 2, 3, 1, 2, 3]


[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


But thats not what we would usually want. Can you think of a way to sum up each elemt in list 1 and 2 to get the result [5,7,9]?

In [6]:
# Hint use a loop

Here is the exact same code just using numpy

In [5]:
# NumPy array operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# This will add the arrays element-wise
print(arr1 + arr2)  # Outputs: array([5, 7, 9])

# This will multiply each element of arr1 by 3
print(arr1 * 3)  # Outputs: array([3, 6, 9])


[5 7 9]
[3 6 9]


### Indexing

Both Python lists and NumPy arrays support basic indexing and slicing. However, NumPy arrays offer advanced indexing options that aren't available with Python lists.

With Python lists, you can access a single element or a slice of elements using their indices:

In [6]:
# Python list indexing
my_list = [1, 2, 3, 4, 5]

print(my_list[0])  # Outputs: 1
print(my_list[1:4])  # Outputs: [2, 3, 4]


1
[2, 3, 4]


NumPy arrays support all of the indexing options that Python lists do, but they also provide powerful ways to access data using boolean indexing and multi-dimensional slicing.

In [7]:
# NumPy array indexing
my_array = np.array([1, 2, 3, 4, 5])

# Boolean indexing
print(my_array[my_array > 3])  # Outputs: array([4, 5])

# Multi-dimensional array slicing
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_2d_array[1:, :2])  # Outputs: array([[4, 5], [7, 8]])


[4 5]
[[4 5]
 [7 8]]


If you want a more detailed look at what other things you can do with numpy feel free to read the documentaion:
- https://numpy.org/doc/1.25/


### Exercises to numpy 

#### Exercise 1: NumPy Array Creation and Operations

- Create a NumPy array 'a' containing the numbers from 1-10.
- Create another NumPy array 'b' containing the numbers from 11-20.
- Perform the following operations:
- Add array 'a' and 'b'
- Subtract array 'b' from 'a'
- Multiply array 'a' by 'b'

In [12]:
# Code here
# Hint: look at documentation for np.linspace()

#### Exercise 2: Python List and NumPy Array Comparison

- Create a Python list and a NumPy array, each containing the numbers from 1-1000000.
- Use the `time` module to compare the time taken to sum the elements in the list vs. the NumPy array. Which is faster?

In [13]:
import time
#Code here

#### Exercise 3: Indexing with NumPy Arrays

Given the following 2D array:

In [14]:
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])


- Access the element at the 2nd row and 3rd column.
- Access the first two rows.
- Access the last two columns.
- Use boolean indexing to print out all the numbers greater than 10.

In [15]:
# Code here

## Pandas

Pandas is a library used for data manipulation and analysis. It provides data structures and functions needed to manipulate structured data.

Read this article on what Structured data is
https://www.tibco.com/reference-center/what-is-structured-data

### Pandas Series

A `Series` is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). It is similar to a column in a spreadsheet, a field in a database, or a vector in R.

In [19]:
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)


0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


### Creating a Data Frame

A DataFrame is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dictionary of Series objects. It is generally the most commonly used pandas object.

In [44]:
df = pd.DataFrame({
    'A': 1.,
    'B': pd.Timestamp('20230705'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E': pd.Categorical(["test", "train", "test", "train"]),
    'F': 'foo'
})

df





A          B    C  D      E    F
0  1.0 2023-07-05  1.0  3   test  foo
1  1.0 2023-07-05  1.0  3  train  foo
2  1.0 2023-07-05  1.0  3   test  foo
3  1.0 2023-07-05  1.0  3  train  foo

### Reading Data

Pandas can read data from various file formats such as CSV, Excel, JSON, SQL databases, html, and even the clipboard.

In [43]:
# Reading data from a html
df_wiki = pd.read_html('https://en.wikipedia.org/wiki/Moons_of_Jupiter')
# returns -> list of data frames
len(df_wiki)

13

In [40]:
jupiter_df = df_wiki[2]# index to access the frame
jupiter_df

Label[note 4]      Name    Pronunciation  Image Abs.magn.[65]  \
0           XVI     Metis        /ˈmiːtəs/    NaN          10.5   
1            XV  Adrastea     /ædrəˈstiːə/    NaN          12.0   
2             V  Amalthea  /æməlˈθiːə/[67]    NaN           7.1   
3           XIV     Thebe        /ˈθiːbiː/    NaN           9.0   
4             I       Io♠          /ˈaɪoʊ/    NaN          –1.7   

     Diameter (km)[4][note 5] Mass(×1016 kg)[66][note 6]  \
0            43(60 × 40 × 34)                      ≈ 3.6   
1          16.4(20 × 16 × 14)                     ≈ 0.20   
2        167(250 × 146 × 128)                        208   
3         98.6(116 × 98 × 84)                       ≈ 43   
4  3643.2(3660 × 3637 × 3631)                    8931900   

   Semi-major axis(km)[62] Orbital period (d)[62][note 7] Inclination(°)[62]  \
0                   128000           +0.2948(+7h 04m 29s)              0.060   
1                   129000           +0.2983(+7h 09m 30s)              0.030   
2                   181400          +0.4999(+11h 59m 53s)              0.374   
3                   221900          +0.6761(+16h 13m 35s)              1.076   
4                   421800       +1.7627(+1d 18h 18m 20s)          0.050[68]   

   Eccentricity[4] Discovery year[1]  Year announced   Discoverer[48][1]  \
0           0.0002              1979            1980  Synnott(Voyager 1)   
1           0.0015              1979            1979   Jewitt(Voyager 2)   
2           0.0032              1892            1892             Barnard   
3           0.0175              1979            1980  Synnott(Voyager 1)   
4           0.0041              1610            1610             Galileo   

  Group[note 8]  
0         Inner  
1         Inner  
2         Inner  
3         Inner  
4      Galilean

In [42]:
jupiter_df.info() #displays some info about your data like dtypes, null counts, and column names. You would have to do some cleaning to fix the columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Label[note 4]                   72 non-null     object 
 1   Name                            95 non-null     object 
 2   Pronunciation                   57 non-null     object 
 3   Image                           0 non-null      float64
 4   Abs.magn.[65]                   95 non-null     object 
 5   Diameter (km)[4][note 5]        95 non-null     object 
 6   Mass(×1016 kg)[66][note 6]      95 non-null     object 
 7   Semi-major axis(km)[62]         95 non-null     int64  
 8   Orbital period (d)[62][note 7]  95 non-null     object 
 9   Inclination(°)[62]              95 non-null     object 
 10  Eccentricity[4]                 95 non-null     float64
 11  Discovery year[1]               95 non-null     object 
 12  Year announced                  95 non

### Query and Masking

You can query your data in different ways. You can select by postion, by label, or even with a boolean array (masking).

In [46]:
# Querying by position
print(df.iloc[0])  # Gets the first row
print(df.iloc[0, 0])  # Gets the first element of the first row

# Querying by label
print(df.loc[0, 'A'])  # Gets the first element of column 'A'

# Boolean indexing or masking
print(df[df['A'] > 0])  # Gets rows where 'A' is greater than 0

# Query using query function
print(df.query("A > 0"))

A                    1.0
B    2023-07-05 00:00:00
C                    1.0
D                      3
E                   test
F                    foo
Name: 0, dtype: object
1.0
1.0
     A          B    C  D      E    F
0  1.0 2023-07-05  1.0  3   test  foo
1  1.0 2023-07-05  1.0  3  train  foo
2  1.0 2023-07-05  1.0  3   test  foo
3  1.0 2023-07-05  1.0  3  train  foo
     A          B    C  D      E    F
0  1.0 2023-07-05  1.0  3   test  foo
1  1.0 2023-07-05  1.0  3  train  foo
2  1.0 2023-07-05  1.0  3   test  foo
3  1.0 2023-07-05  1.0  3  train  foo


### Summary Statistics

Pandas provides a large number of methods to extract key statistical information from your data.

In [47]:
# Getting summary statistics of the dataframe
print(df.describe())

# Counting non-NA cells for each column
print(df.count())

# Calculating mean
print(df.mean())

# Getting min, max values
print(df.min())
print(df.max())

# Applying a function to the data
print(df.apply(np.cumsum))  # Cumulative sum over data


         A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0
A    4
B    4
C    4
D    4
E    4
F    4
dtype: int64
A    1.0
C    1.0
D    3.0
dtype: float64
A                    1.0
B    2023-07-05 00:00:00
C                    1.0
D                      3
F                    foo
dtype: object
A                    1.0
B    2023-07-05 00:00:00
C                    1.0
D                      3
F                    foo
dtype: object
     A          B    C   D                   E             F
0  1.0 2023-07-05  1.0   3                test           foo
1  2.0 2077-01-05  2.0   6           testtrain        foofoo
2  3.0 2130-07-10  3.0   9       testtraintest     foofoofoo
3  4.0 2184-01-11  4.0  12  testtraintesttrain  foofoofoofoo


C:\Users\alexg\AppData\Local\Temp\ipykernel_39832\1280724371.py:8: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  print(df.mean())
C:\Users\alexg\AppData\Local\Temp\ipykernel_39832\1280724371.py:8: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.mean())
C:\Users\alexg\AppData\Local\Temp\ipykernel_39832\1280724371.py:11: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.min())
C:\Users\alexg\AppData\Local\Temp\ipykernel_39832\1280724371.py:12: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is depr

### Exercises to pandas

#### Exercise 1: Creating a DataFrame object

Create a DataFrame 'df' with the following structure:

| Index | Name | Age | City | Income |
| --- | --- | --- | --- | --- |
| 0 | Alex | 21 | New York | 60000 |
| 1 | Bob | 24 | California | 70000 |
| 2 | Mark | 25 | Texas | 80000 |


#### Exercise 2: Reading and Querying Data

- Load a dataset from a CSV file named 'Iris.csv' into a DataFrame 'df'.
- Display the first 5 rows of the DataFrame.
- Display the last 5 rows of the DataFrame.
- Show the information of iris flower that have a sepal length greater than 5cm and a petal length between 1 and 4 cm

In [61]:
#Code Here

#### Exercise 3: Summary Statistics

Given the DataFrame 'df' created in Exercise 1:

- Calculate the mean income.
- Identify the person with the highest income.
- Identify the person with the lowest age.

In [ ]:
#Code Here

## Solutions to Exercises

### Numpy Solutions

#### Ex1

In [ ]:
# 1.
a = np.arange(1, 11)
# 2.
b = np.arange(11, 21)
# 3.
print(a + b)
print(a - b)
print(a * b)


#### Ex2

In [ ]:
import time

# 1.
python_list = list(range(1, 1000001))
numpy_array = np.arange(1, 1000001)

# 2.
start = time.time()
sum_list = sum(python_list)
end = time.time()
print("Time taken by Python list: ", end - start)

start = time.time()
sum_array = numpy_array.sum()
end = time.time()
print("Time taken by NumPy array: ", end - start)


#### Ex3

In [ ]:
# 1.
print(array[1, 2])

# 2.
print(array[:2, :])

# 3.
print(array[:, -2:])

# 4.
print(array[array > 10])


## Pandas Solutions

### Ex 1

In [62]:
df = pd.DataFrame({
    'Name': ['Alex', 'Bob', 'Mark'],
    'Age': [21, 24, 25],
    'City': ['New York', 'California', 'Texas'],
    'Income': [60000, 70000, 80000]
})


### Ex 2

In [65]:
# 1.
df = pd.read_csv('Iris.csv')

# 2.
print(df.head(5))

# 3.
print(df.tail(5))

# 4.
print(df.query("SepalLengthCm > 5 & (PetalLengthCm > 1 & PetalLengthCm < 4) "))


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Ir